update of computation extension due to feedback from the siibra-team
HumanBrainProject/openMINDS_computation pull request #48
Opened 2023-02-15 09:10 UTC by lzehl

2023-02-15 11:29 UTC, UlrikeS91 requested changes

2023-02-15 11:29 UTC, UlrikeS91 commented on schemas/computation.schema.tpl.json
> +      "_instruction": "Add one or several analysis techniques that were used in this computation.",
"Add all analysis techniques that were used during this activity."
(in accordance with the clean up)

2023-02-15 13:14 UTC, apdavison approved these changes

2023-02-17 10:07 UTC, UlrikeS91 approved these changes

2023-02-17 10:07 UTC, merged